# Generated by Django 5.0 on 2024-02-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("sno", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField(max_length=200)),
                ("slug", models.CharField(max_length=100)),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
