# Generated by Django 5.0 on 2024-02-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("sno", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=20)),
                ("desc", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=models.TextField(),
        ),
    ]
